buildscript {
    repositories {
        mavenCentral()
        maven {
            name = "forge"
            url = "https://maven.minecraftforge.net"
        }
    }
    dependencies {
        classpath("com.anatawa12.forge:ForgeGradle:2.3-1.0.+") {
            changing = true
        }
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'
apply plugin: 'groovy'
apply plugin: 'java'

group = "com.artur114.srptowerdefense"
archivesBaseName = "SRPTowerDefense"
version = mod_version

repositories {
    maven {url 'https://jitpack.io'}
}

configurations {
    include; implementation.extendsFrom(include)
}

dependencies {
    include('com.github.Artur114Projects.BananaLib:asm:1.0.5-betta') {transitive=false}
    include('com.github.Artur114Projects.BananaLib:util:1.0.5-betta') {transitive=false}
    include('com.github.Artur114Projects.BananaLib:math:1.0.5-betta') {transitive=false}
    include('com.github.Artur114Projects.BananaLib:mc:1.0.5-betta') {transitive=false}

//    implementation fileTree(dir: "libs", includes: ['*.jar'])
    implementation 'com.github.Artur114Projects.BananaLib:math-groovy:1.0.5-betta'
    implementation 'org.jetbrains:annotations:24.0.0'
    implementation localGroovy()
}

minecraft {
    runDir = 'run'
    version = "1.12.2-14.23.5.2847"
    mappings = "snapshot_20171003"
    clientRunArgs += ["--uuid", "11111111-1111-1111-1111-111111111111"]
}

processResources {
    Map replaceProperties = [mod_version: mod_version, build_id: new Date().format("dd'.'MM'.'yyy'-'HH:mm:ss") + "-UTC+3"]
    List includeFiles = ["mcmod.info"]

    inputs.properties replaceProperties

    filesMatching(includeFiles) {
        it.expand(replaceProperties)
    }
}

jar {
    from {
        configurations.include.collect {
            it.isDirectory() ? it : zipTree(it)
        }
    }
    manifest {
        attributes([
            "Implementation-Vendor": mod_author,
            "Implementation-Version": mod_version,
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
            "Included-Libs": "[${configurations.include.collect{it.name.substring(0, it.name.lastIndexOf('.'))}.join(", ")}]",
            "FMLAT": 'td_at.cfg'
        ])
    }
}

tasks.register("openOut") {
    doLast {
        if (System.getProperty("os.name").toLowerCase().contains("win")) {
            try {
                new ProcessBuilder(
                        "explorer", "/select,",
                        file("build/libs/${archivesBaseName}-${version}.jar").absolutePath
                ).start()
            } catch (IOException e) {
                e.printStackTrace()
            }
        }
    }
}

build.finalizedBy(tasks.named("openOut"))