package com.artur114.bananalib.math.m2d.vec;

import com.artur114.bananalib.math.m2d.area.IBox2D;
import com.artur114.bananalib.math.m2d.area.IBox2I;
import com.artur114.bananalib.math.m3d.vec.IVec3D;
import com.artur114.bananalib.math.m3d.vec.IVec3I;

public interface IVec2I {
    int x();
    int y();
    IVec2I yx();
    IVec3I xyz(int z);
    IVec3I xzy(int z);
    IVec3I zxy(int z);
    IVec2D yxD();
    IVec3D xyzD(double z);
    IVec3D xzyD(double z);
    IVec3D zxyD(double z);
    float length();
    float lengthSq();
    int dot(IVec2I vec);
    double dot(IVec2D vec);
    int cross(IVec2I vec);
    double cross(IVec2D vec);
    float distance(int x, int y);
    float distance(double x, double y);
    float distance(IVec2I vec);
    float distance(IVec2D vec);
    float distanceSq(int x, int y);
    float distanceSq(double x, double y);
    float distanceSq(IVec2I vec);
    float distanceSq(IVec2D vec);
    IVec2I add(int x, int y);
    IVec2I add(double x, double y);
    IVec2I add(IVec2I vec);
    IVec2I add(IVec2D vec);
    IVec2I subtract(int x, int y);
    IVec2I subtract(double x, double y);
    IVec2I subtract(IVec2I vec);
    IVec2I subtract(IVec2D vec);
    IVec2I scale(int val);
    IVec2I scale(int x, int y);
    IVec2I scale(double val);
    IVec2I scale(double x, double y);
    IVec2I scale(IVec2I vec);
    IVec2I scale(IVec2D vec);
    IVec2I divide(int val);
    IVec2I divide(int x, int y);
    IVec2I divide(double val);
    IVec2I divide(double x, double y);
    IVec2I divide(IVec2I vec);
    IVec2I divide(IVec2D vec);
    IVec2I rotate(double degrees);
    IVec2I rotateAround(int x, int y, double degrees);
    IVec2I rotateAround(double x, double y, double degrees);
    IVec2I rotateAround(IVec2D point, double degrees);
    IVec2I rotateAround(IVec2I point, double degrees);
    IVec2I wrap(IBox2I box);
    IVec2I wrap(IBox2D box);
    IVec2I wrap(int x, int y);
    IVec2I wrap(double x, double y);
    IVec2I wrap(int minX, int minY, int maxX, int maxY);
    IVec2I wrap(double minX, double minY, double maxX, double maxY);
    IVec2I clamp(IBox2I box);
    IVec2I clamp(IBox2D box);
    IVec2I clamp(int x, int y);
    IVec2I clamp(double x, double y);
    IVec2I clamp(int minX, int minY, int maxX, int maxY);
    IVec2I clamp(double minX, double minY, double maxX, double maxY);
    IVec2D normalize();
    IVec2IM toMutable();
    IVec2I toImmutable();
    IVec2D toDouble();
    IVec2I copy();
}
