package com.artur114.bananalib.math.m2d.vec;

public interface IVec2I {
    int x();
    int y();
    IVec2I yx();
    IVec2D yxD();
    float length();
    float lengthSq();
    int dot(IVec2I vec);
    double dot(IVec2D vec);
    int cross(IVec2I vec);
    double cross(IVec2D vec);
    float distance(int x, int y);
    float distance(double x, double y);
    float distance(IVec2I vec);
    float distance(IVec2D vec);
    float distanceSq(int x, int y);
    float distanceSq(double x, double y);
    float distanceSq(IVec2I vec);
    float distanceSq(IVec2D vec);
    IVec2I add(int x, int y);
    IVec2I add(double x, double y);
    IVec2I add(IVec2I vec);
    IVec2I add(IVec2D vec);
    IVec2I subtract(int x, int y);
    IVec2I subtract(double x, double y);
    IVec2I subtract(IVec2I vec);
    IVec2I subtract(IVec2D vec);
    IVec2I scale(int val);
    IVec2I scale(int x, int y);
    IVec2I scale(double val);
    IVec2I scale(double x, double y);
    IVec2I scale(IVec2I vec);
    IVec2I scale(IVec2D vec);
    IVec2I rotate(double degrees);
    IVec2I rotateAround(int x, int y, double degrees);
    IVec2I rotateAround(double x, double y, double degrees);
    IVec2I rotateAround(IVec2D point, double degrees);
    IVec2I rotateAround(IVec2I point, double degrees);
    IVec2D normalize();
    IVec2IM toMutable();
    IVec2I toImmutable();
    IVec2D toDouble();
}
