package com.artur114.srptowerdefense.common.init;

import com.artur114.bananalib.mc.registry.ann.AutoInstantiate;
import com.artur114.bananalib.mc.registry.interf.ILoadStagePost;
import com.artur114.srptowerdefense.common.worldstate.blockdamage.registry.EntityDamageRegistry;

@AutoInstantiate
public class InitEntityDamage implements ILoadStagePost {
    @Override
    public void onPostInit() {
        EntityDamageRegistry.registerEntity("srparasites:sim_bigspider", 1000, 0.5F);
        EntityDamageRegistry.registerEntity("srparasites:sim_squid", 1000, 0.5F);
        EntityDamageRegistry.registerEntity("srparasites:sim_bear", 2000, 0.4F);
        EntityDamageRegistry.registerEntity("srparasites:sim_human", 1000, 0.4F);
        EntityDamageRegistry.registerEntity("srparasites:sim_humanhead", 200, 0.8F);
        EntityDamageRegistry.registerEntity("srparasites:sim_enderman", 1500, 0.4F);
        EntityDamageRegistry.registerEntity("srparasites:sim_endermanhead", 200, 0.8F);
        EntityDamageRegistry.registerEntity("srparasites:sim_cow", 800, 0.5F);
        EntityDamageRegistry.registerEntity("srparasites:sim_cowhead", 200, 0.8F);
        EntityDamageRegistry.registerEntity("srparasites:sim_sheep", 700, 0.5F);
        EntityDamageRegistry.registerEntity("srparasites:sim_sheephead", 200, 0.8F);
        EntityDamageRegistry.registerEntity("srparasites:sim_wolf", 600, 0.3F);
        EntityDamageRegistry.registerEntity("srparasites:sim_wolfhead", 200, 0.8F);
        EntityDamageRegistry.registerEntity("srparasites:sim_pig", 800, 0.4F);
        EntityDamageRegistry.registerEntity("srparasites:sim_pighead", 200, 0.8F);
        EntityDamageRegistry.registerEntity("srparasites:sim_villager", 1000, 0.4F);
        EntityDamageRegistry.registerEntity("srparasites:sim_villagerhead", 200, 0.8F);
        EntityDamageRegistry.registerEntity("srparasites:sim_adventurer", 1200, 0.4F);
        EntityDamageRegistry.registerEntity("srparasites:sim_adventurerhead", 200, 0.8F);
        EntityDamageRegistry.registerEntity("srparasites:sim_dragone", 6000, 1.0F);
        EntityDamageRegistry.registerEntity("srparasites:sim_dragonehead", 2000, 1.0F);
        EntityDamageRegistry.registerEntity("srparasites:fer_bear", 6000, 0.2F);
        EntityDamageRegistry.registerEntity("srparasites:fer_human", 4000, 0.2F);
        EntityDamageRegistry.registerEntity("srparasites:fer_cow", 4000, 0.2F);
        EntityDamageRegistry.registerEntity("srparasites:fer_enderman", 4000, 0.05F);
        EntityDamageRegistry.registerEntity("srparasites:fer_horse", 4000, 0.2F);
        EntityDamageRegistry.registerEntity("srparasites:fer_pig", 3000, 0.2F);
        EntityDamageRegistry.registerEntity("srparasites:fer_sheep", 4000, 0.2F);
        EntityDamageRegistry.registerEntity("srparasites:fer_villager", 4000, 0.2F);
        EntityDamageRegistry.registerEntity("srparasites:fer_wolf", 3000, 0.1F);
        EntityDamageRegistry.registerEntity("srparasites:mar_cow", 5000, 0.5F);
        EntityDamageRegistry.registerEntity("srparasites:mar_enderman", 3000, 0.4F);
        EntityDamageRegistry.registerEntity("srparasites:mar_villager", 6000, 0.5F);
        EntityDamageRegistry.registerEntity("srparasites:mar_human", 5000, 0.5F);
        EntityDamageRegistry.registerEntity("srparasites:mar_sheep", 6000, 0.5F);
        EntityDamageRegistry.registerEntity("srparasites:mar_bear", 8000, 0.5F);
        EntityDamageRegistry.registerEntity("srparasites:hi_golem", 5000, 0.5F);
        EntityDamageRegistry.registerEntity("srparasites:hi_blaze", 2000, 0.3F);
        EntityDamageRegistry.registerEntity("srparasites:hi_skeleton", 2000, 0.3F);
        EntityDamageRegistry.registerEntity("srparasites:host", 2000, 1.0F);
        EntityDamageRegistry.registerEntity("srparasites:hostii", 3000, 1.0F);
        EntityDamageRegistry.registerEntity("srparasites:heed", 5000, 0.5F);
        EntityDamageRegistry.registerEntity("srparasites:crux", 16000, 0.5F);
        EntityDamageRegistry.registerEntity("srparasites:thrall", 4000, 0.4F);
        EntityDamageRegistry.registerEntity("srparasites:movingflesh", 200, 1.0F);
        EntityDamageRegistry.registerEntity("srparasites:dredge", 4000, 0.2F);
        EntityDamageRegistry.registerEntity("srparasites:crux_incomplete", 1000, 1.0F);
        EntityDamageRegistry.registerEntity("srparasites:abo_bodies", 7000, 1.0F);
        EntityDamageRegistry.registerEntity("srparasites:pri_longarms", 4000, 0.25F);
        EntityDamageRegistry.registerEntity("srparasites:pri_summoner", 3000, 0.3F);
        EntityDamageRegistry.registerEntity("srparasites:pri_reeker", 4000, 0.2F);
        EntityDamageRegistry.registerEntity("srparasites:pri_manducater", 3000, 0.5F);
        EntityDamageRegistry.registerEntity("srparasites:pri_yelloweye", 2000, 0.5F);
        EntityDamageRegistry.registerEntity("srparasites:pri_bolster", 3000, 0.5F);
        EntityDamageRegistry.registerEntity("srparasites:pri_tozoon", 4000, 0.5F);
        EntityDamageRegistry.registerEntity("srparasites:pri_vermin", 2000, 0.5F);
        EntityDamageRegistry.registerEntity("srparasites:pri_arachnida", 3000, 0.25F);
        EntityDamageRegistry.registerEntity("srparasites:pri_devourer", 3000, 0.5F);
        EntityDamageRegistry.registerEntity("srparasites:pri_viscera", 4000, 0.5F);
        EntityDamageRegistry.registerEntity("srparasites:pri_burrower", 4000, 0.5F);
        EntityDamageRegistry.registerEntity("srparasites:ada_longarms", 6000, 0.2F);
        EntityDamageRegistry.registerEntity("srparasites:ada_summoner", 6000, 0.25F);
        EntityDamageRegistry.registerEntity("srparasites:ada_manducater", 4000, 0.4F);
        EntityDamageRegistry.registerEntity("srparasites:ada_yelloweye", 4000, 0.5F);
        EntityDamageRegistry.registerEntity("srparasites:ada_bolster", 6000, 0.15F);
        EntityDamageRegistry.registerEntity("srparasites:ada_vermin", 4000, 1.0F);
        EntityDamageRegistry.registerEntity("srparasites:ada_arachnida", 4000, 0.25F);
        EntityDamageRegistry.registerEntity("srparasites:ada_devourer", 6000, 0.5F);
        EntityDamageRegistry.registerEntity("srparasites:ada_viscera", 6000, 0.15F);
        EntityDamageRegistry.registerEntity("srparasites:buglin", 100, 0.5F);
        EntityDamageRegistry.registerEntity("srparasites:rupter", 600, 0.4F);
        EntityDamageRegistry.registerEntity("srparasites:mangler", 2000, 0.15F);
        EntityDamageRegistry.registerEntity("srparasites:gnat", 100, 0.5F);
        EntityDamageRegistry.registerEntity("srparasites:carrier_heavy", 2000, 2.0F);
        EntityDamageRegistry.registerEntity("srparasites:carrier_light", 1000, 1.0F);
        EntityDamageRegistry.registerEntity("srparasites:carrier_flying", 1000, 1.0F);
        EntityDamageRegistry.registerEntity("srparasites:overseer", 4000, 0.15F);
        EntityDamageRegistry.registerEntity("srparasites:warden", 6000, 0.1F);
        EntityDamageRegistry.registerEntity("srparasites:bomber_light", 6000, 1.0F);
        EntityDamageRegistry.registerEntity("srparasites:marauder", 6000, 0.1F);
        EntityDamageRegistry.registerEntity("srparasites:monarch", 6000, 0.05F);
        EntityDamageRegistry.registerEntity("srparasites:grunt", 4000, 0.15F);
        EntityDamageRegistry.registerEntity("srparasites:vigilante", 6000, 0.1F);
        EntityDamageRegistry.registerEntity("srparasites:bomber_heavy", 10000, 2.0F);
        EntityDamageRegistry.registerEntity("srparasites:carrier_colony", 8000, 0.5F);
        EntityDamageRegistry.registerEntity("srparasites:haunter", 10000, 0.5F);
        EntityDamageRegistry.registerEntity("srparasites:bogle", 6000, 0.5F);
        EntityDamageRegistry.registerEntity("srparasites:draconite", 10000, 0.1F);
        EntityDamageRegistry.registerEntity("srparasites:kirin", 12000, 0.5F);
    }
}
