package com.artur114.bananalib.math.m3d.vec;


import com.artur114.bananalib.math.m2d.vec.IVec2D;
import com.artur114.bananalib.math.m2d.vec.IVec2I;

public interface IVec3D {
    double x();
    double y();
    double z();
    IVec2D xy();
    IVec2D xz();
    IVec2D yx();
    IVec2D yz();
    IVec2D zx();
    IVec2D zy();
    IVec3D zyx();
    IVec2I xyI();
    IVec2I xzI();
    IVec2I yxI();
    IVec2I yzI();
    IVec2I zxI();
    IVec2I zyI();
    IVec3I zyxI();
    double length();
    double lengthSq();
    double dot(IVec3I vec);
    double dot(IVec3D vec);
    IVec3D cross(IVec3I vec);
    IVec3D cross(IVec3D vec);
    double distance(int x, int y, int z);
    double distance(double x, double y, double z);
    double distance(IVec3I vec);
    double distance(IVec3D vec);
    double distanceSq(int x, int y, int z);
    double distanceSq(double x, double y, double z);
    double distanceSq(IVec3I vec);
    double distanceSq(IVec3D vec);
    IVec3D add(int x, int y, int z);
    IVec3D add(double x, double y, double z);
    IVec3D add(IVec3I vec);
    IVec3D add(IVec3D vec);
    IVec3D add(IVec2I vec, int z);
    IVec3D add(IVec2I vec, double z);
    IVec3D add(IVec2D vec, int z);
    IVec3D add(IVec2D vec, double z);
    IVec3D add(IVec2I vec);
    IVec3D add(IVec2D vec);
    IVec3D subtract(int x, int y, int z);
    IVec3D subtract(double x, double y, double z);
    IVec3D subtract(IVec3I vec);
    IVec3D subtract(IVec3D vec);
    IVec3D subtract(IVec2I vec, int z);
    IVec3D subtract(IVec2I vec, double z);
    IVec3D subtract(IVec2D vec, int z);
    IVec3D subtract(IVec2D vec, double z);
    IVec3D subtract(IVec2I vec);
    IVec3D subtract(IVec2D vec);
    IVec3D scale(int x, int y, int z);
    IVec3D scale(double x, double y, double z);
    IVec3D scale(IVec3I vec);
    IVec3D scale(IVec3D vec);
    IVec3D scale(IVec2I vec, int z);
    IVec3D scale(IVec2I vec, double z);
    IVec3D scale(IVec2D vec, int z);
    IVec3D scale(IVec2D vec, double z);
    IVec3D scale(IVec2I vec);
    IVec3D scale(IVec2D vec);
    IVec3D rotateX(double degrees);
    IVec3D rotateY(double degrees);
    IVec3D rotateZ(double degrees);
    IVec3D rotateXAround(int x, int y, int z, double degrees);
    IVec3D rotateXAround(double x, double y, double z, double degrees);
    IVec3D rotateXAround(IVec3I point, double degrees);
    IVec3D rotateXAround(IVec3D point, double degrees);
    IVec3D rotateYAround(int x, int y, int z, double degrees);
    IVec3D rotateYAround(double x, double y, double z, double degrees);
    IVec3D rotateYAround(IVec3I point, double degrees);
    IVec3D rotateYAround(IVec3D point, double degrees);
    IVec3D rotateZAround(int x, int y, int z, double degrees);
    IVec3D rotateZAround(double x, double y, double z, double degrees);
    IVec3D rotateZAround(IVec3I point, double degrees);
    IVec3D rotateZAround(IVec3D point, double degrees);
    IVec3D normalize();
    IVec3DM toMutable();
    IVec3D toImmutable();
    IVec3I toInt();
}
