package com.artur114.bananalib.math.m3d.vec;

import com.artur114.bananalib.math.m2d.vec.IVec2D;
import com.artur114.bananalib.math.m2d.vec.IVec2DM;
import com.artur114.bananalib.math.m2d.vec.IVec2I;

public interface IVec3DM extends IVec3D {
    IVec3DM set(double[] pos);
    IVec3DM set(double x, double y, double z);
    IVec3DM set(int x, int y, int z);
    IVec3DM set(IVec3I vec);
    IVec3DM set(IVec3D vec);
    IVec3DM set(IVec2D vec, double z);
    IVec3DM set(IVec2D vec, int z);
    IVec3DM set(IVec2I vec, double z);
    IVec3DM set(IVec2I vec, int z);
    IVec3DM set(IVec2D vec);
    IVec3DM set(IVec2I vec);
    IVec3DM setZero();
    IVec3DM collapseStack();
    IVec3DM resetStack();
    IVec3DM pushPos();
    IVec3DM popPos();
    IVec3DM setX(int x);
    IVec3DM setY(int y);
    IVec3DM setZ(int z);
    IVec3DM add(int x, int y, int z);
    IVec3DM add(double x, double y, double z);
    IVec3DM add(IVec3I vec);
    IVec3DM add(IVec3D vec);
    IVec3DM add(IVec2I vec, int z);
    IVec3DM add(IVec2I vec, double z);
    IVec3DM add(IVec2D vec, int z);
    IVec3DM add(IVec2D vec, double z);
    IVec3DM add(IVec2I vec);
    IVec3DM add(IVec2D vec);
    IVec3DM subtract(int x, int y, int z);
    IVec3DM subtract(double x, double y, double z);
    IVec3DM subtract(IVec3I vec);
    IVec3DM subtract(IVec3D vec);
    IVec3DM subtract(IVec2I vec, int z);
    IVec3DM subtract(IVec2I vec, double z);
    IVec3DM subtract(IVec2D vec, int z);
    IVec3DM subtract(IVec2D vec, double z);
    IVec3DM subtract(IVec2I vec);
    IVec3DM subtract(IVec2D vec);
    IVec3DM scale(int x, int y, int z);
    IVec3DM scale(double x, double y, double z);
    IVec3DM scale(IVec3I vec);
    IVec3DM scale(IVec3D vec);
    IVec3DM scale(IVec2I vec, int z);
    IVec3DM scale(IVec2I vec, double z);
    IVec3DM scale(IVec2D vec, int z);
    IVec3DM scale(IVec2D vec, double z);
    IVec3DM scale(IVec2I vec);
    IVec3DM scale(IVec2D vec);
    IVec3DM rotateX(double degrees);
    IVec3DM rotateY(double degrees);
    IVec3DM rotateZ(double degrees);
    IVec3DM rotateXAround(int x, int y, int z, double degrees);
    IVec3DM rotateXAround(double x, double y, double z, double degrees);
    IVec3DM rotateXAround(IVec3I point, double degrees);
    IVec3DM rotateXAround(IVec3D point, double degrees);
    IVec3DM rotateYAround(int x, int y, int z, double degrees);
    IVec3DM rotateYAround(double x, double y, double z, double degrees);
    IVec3DM rotateYAround(IVec3I point, double degrees);
    IVec3DM rotateYAround(IVec3D point, double degrees);
    IVec3DM rotateZAround(int x, int y, int z, double degrees);
    IVec3DM rotateZAround(double x, double y, double z, double degrees);
    IVec3DM rotateZAround(IVec3I point, double degrees);
    IVec3DM rotateZAround(IVec3D point, double degrees);
    IVec3DM normalize();
    IVec3IM toInt();
}
