package com.artur114.bananalib.math.m3d.vec;

import com.artur114.bananalib.math.m2d.area.IBox2D;
import com.artur114.bananalib.math.m2d.area.IBox2I;
import com.artur114.bananalib.math.m2d.vec.IVec2D;
import com.artur114.bananalib.math.m2d.vec.IVec2DM;
import com.artur114.bananalib.math.m2d.vec.IVec2I;
import com.artur114.bananalib.math.m3d.box.IBox3D;
import com.artur114.bananalib.math.m3d.box.IBox3I;

public interface IVec3DM extends IVec3D {
    IVec3DM set(double[] pos);
    IVec3DM set(double x, double y, double z);
    IVec3DM set(int x, int y, int z);
    IVec3DM set(IVec3I vec);
    IVec3DM set(IVec3D vec);
    IVec3DM set(IVec2D vec, double z);
    IVec3DM set(IVec2D vec, int z);
    IVec3DM set(IVec2I vec, double z);
    IVec3DM set(IVec2I vec, int z);
    IVec3DM set(IVec2D vec);
    IVec3DM set(IVec2I vec);
    IVec3DM setZero();
    IVec3DM collapseStack();
    IVec3DM resetStack();
    IVec3DM pushPos();
    IVec3DM popPos();
    IVec3DM setX(int x);
    IVec3DM setX(double x);
    IVec3DM setY(int y);
    IVec3DM setY(double y);
    IVec3DM setZ(int z);
    IVec3DM setZ(double z);
    IVec3DM add(int x, int y, int z);
    IVec3DM add(double x, double y, double z);
    IVec3DM add(IVec3I vec);
    IVec3DM add(IVec3D vec);
    IVec3DM add(IVec2I vec, int z);
    IVec3DM add(IVec2I vec, double z);
    IVec3DM add(IVec2D vec, int z);
    IVec3DM add(IVec2D vec, double z);
    IVec3DM add(IVec2I vec);
    IVec3DM add(IVec2D vec);
    IVec3DM subtract(int x, int y, int z);
    IVec3DM subtract(double x, double y, double z);
    IVec3DM subtract(IVec3I vec);
    IVec3DM subtract(IVec3D vec);
    IVec3DM subtract(IVec2I vec, int z);
    IVec3DM subtract(IVec2I vec, double z);
    IVec3DM subtract(IVec2D vec, int z);
    IVec3DM subtract(IVec2D vec, double z);
    IVec3DM subtract(IVec2I vec);
    IVec3DM subtract(IVec2D vec);
    IVec3DM scale(int val);
    IVec3DM scale(double val);
    IVec3DM scale(int x, int y, int z);
    IVec3DM scale(double x, double y, double z);
    IVec3DM scale(IVec3I vec);
    IVec3DM scale(IVec3D vec);
    IVec3DM scale(IVec2I vec, int z);
    IVec3DM scale(IVec2I vec, double z);
    IVec3DM scale(IVec2D vec, int z);
    IVec3DM scale(IVec2D vec, double z);
    IVec3DM scale(IVec2I vec);
    IVec3DM scale(IVec2D vec);
    IVec3DM divide(int val);
    IVec3DM divide(double val);
    IVec3DM divide(int x, int y, int z);
    IVec3DM divide(double x, double y, double z);
    IVec3DM divide(IVec3I vec);
    IVec3DM divide(IVec3D vec);
    IVec3DM divide(IVec2I vec, int z);
    IVec3DM divide(IVec2I vec, double z);
    IVec3DM divide(IVec2D vec, int z);
    IVec3DM divide(IVec2D vec, double z);
    IVec3DM divide(IVec2I vec);
    IVec3DM divide(IVec2D vec);
    IVec3DM rotateX(double degrees);
    IVec3DM rotateY(double degrees);
    IVec3DM rotateZ(double degrees);
    IVec3DM rotateXAround(int x, int y, int z, double degrees);
    IVec3DM rotateXAround(double x, double y, double z, double degrees);
    IVec3DM rotateXAround(IVec3I point, double degrees);
    IVec3DM rotateXAround(IVec3D point, double degrees);
    IVec3DM rotateYAround(int x, int y, int z, double degrees);
    IVec3DM rotateYAround(double x, double y, double z, double degrees);
    IVec3DM rotateYAround(IVec3I point, double degrees);
    IVec3DM rotateYAround(IVec3D point, double degrees);
    IVec3DM rotateZAround(int x, int y, int z, double degrees);
    IVec3DM rotateZAround(double x, double y, double z, double degrees);
    IVec3DM rotateZAround(IVec3I point, double degrees);
    IVec3DM rotateZAround(IVec3D point, double degrees);
    IVec3DM wrap(IBox3I box);
    IVec3DM wrap(IBox3D box);
    IVec3DM wrap(IBox2I box, int minZ, int maxZ);
    IVec3DM wrap(IBox2I box, double minZ, double maxZ);
    IVec3DM wrap(IBox2D box, int minZ, int maxZ);
    IVec3DM wrap(IBox2D box, double minZ, double maxZ);
    IVec3DM wrap(IBox2I box);
    IVec3DM wrap(IBox2D box);
    IVec3DM wrap(int x, int y, int z);
    IVec3DM wrap(double x, double y, double z);
    IVec3DM wrap(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IVec3DM wrap(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    IVec3DM clamp(IBox3I box);
    IVec3DM clamp(IBox3D box);
    IVec3DM clamp(IBox2I box, int minZ, int maxZ);
    IVec3DM clamp(IBox2I box, double minZ, double maxZ);
    IVec3DM clamp(IBox2D box, int minZ, int maxZ);
    IVec3DM clamp(IBox2D box, double minZ, double maxZ);
    IVec3DM clamp(IBox2I box);
    IVec3DM clamp(IBox2D box);
    IVec3DM clamp(int x, int y, int z);
    IVec3DM clamp(double x, double y, double z);
    IVec3DM clamp(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IVec3DM clamp(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    IVec3DM normalize();
    IVec3IM floor();
    IVec3IM round();
    IVec3IM ceil();
    IVec3DM copy();
}
