package com.artur114.bananalib.math.m3d.vec;

import com.artur114.bananalib.math.m2d.vec.IVec2D;
import com.artur114.bananalib.math.m2d.vec.IVec2I;

public interface IVec3IM extends IVec3I {
    IVec3IM set(double[] pos);
    IVec3IM set(double x, double y, double z);
    IVec3IM set(int x, int y, int z);
    IVec3IM set(IVec3I vec);
    IVec3IM set(IVec3D vec);
    IVec3IM set(IVec2D vec, double z);
    IVec3IM set(IVec2D vec, int z);
    IVec3IM set(IVec2I vec, double z);
    IVec3IM set(IVec2I vec, int z);
    IVec3IM set(IVec2D vec);
    IVec3IM set(IVec2I vec);
    IVec3IM setZero();
    IVec3IM collapseStack();
    IVec3IM resetStack();
    IVec3IM pushPos();
    IVec3IM popPos();
    IVec3IM setX(int x);
    IVec3IM setY(int y);
    IVec3IM setZ(int z);
    IVec3IM add(int x, int y, int z);
    IVec3IM add(double x, double y, double z);
    IVec3IM add(IVec3I vec);
    IVec3IM add(IVec3D vec);
    IVec3IM add(IVec2I vec, int z);
    IVec3IM add(IVec2I vec, double z);
    IVec3IM add(IVec2D vec, int z);
    IVec3IM add(IVec2D vec, double z);
    IVec3IM add(IVec2I vec);
    IVec3IM add(IVec2D vec);
    IVec3IM subtract(int x, int y, int z);
    IVec3IM subtract(double x, double y, double z);
    IVec3IM subtract(IVec3I vec);
    IVec3IM subtract(IVec3D vec);
    IVec3IM subtract(IVec2I vec, int z);
    IVec3IM subtract(IVec2I vec, double z);
    IVec3IM subtract(IVec2D vec, int z);
    IVec3IM subtract(IVec2D vec, double z);
    IVec3IM subtract(IVec2I vec);
    IVec3IM subtract(IVec2D vec);
    IVec3IM scale(int x, int y, int z);
    IVec3IM scale(double x, double y, double z);
    IVec3IM scale(IVec3I vec);
    IVec3IM scale(IVec3D vec);
    IVec3IM scale(IVec2I vec, int z);
    IVec3IM scale(IVec2I vec, double z);
    IVec3IM scale(IVec2D vec, int z);
    IVec3IM scale(IVec2D vec, double z);
    IVec3IM scale(IVec2I vec);
    IVec3IM scale(IVec2D vec);
    IVec3IM rotateX(double degrees);
    IVec3IM rotateY(double degrees);
    IVec3IM rotateZ(double degrees);
    IVec3IM rotateXAround(int x, int y, int z, double degrees);
    IVec3IM rotateXAround(double x, double y, double z, double degrees);
    IVec3IM rotateXAround(IVec3I point, double degrees);
    IVec3IM rotateXAround(IVec3D point, double degrees);
    IVec3IM rotateYAround(int x, int y, int z, double degrees);
    IVec3IM rotateYAround(double x, double y, double z, double degrees);
    IVec3IM rotateYAround(IVec3I point, double degrees);
    IVec3IM rotateYAround(IVec3D point, double degrees);
    IVec3IM rotateZAround(int x, int y, int z, double degrees);
    IVec3IM rotateZAround(double x, double y, double z, double degrees);
    IVec3IM rotateZAround(IVec3I point, double degrees);
    IVec3IM rotateZAround(IVec3D point, double degrees);
    IVec3DM normalize();
    IVec3DM toDouble();
}
