package com.artur114.bananalib.math.m2d.matrix;

import com.artur114.bananalib.math.m2d.area.IBox2D;
import com.artur114.bananalib.math.m2d.area.IBox2DM;
import com.artur114.bananalib.math.m2d.area.IBox2I;
import com.artur114.bananalib.math.m2d.area.IBox2IM;
import com.artur114.bananalib.math.m2d.vec.*;

import java.nio.DoubleBuffer;
import java.nio.FloatBuffer;

public interface IMatrix2F {
    float m00();
    float m01();
    float m02();
    float m10();
    float m11();
    float m12();
    float m20();
    float m21();
    float m22();
    IMatrix2F invert();
    float determinant();
    boolean isReversible();
    IMatrix2F mul(IMatrix2F matrix);
    IMatrix2F mul(IMatrix2D matrix);
    IMatrix2F mulPost(IMatrix2F matrix);
    IMatrix2F mulPost(IMatrix2D matrix);
    IMatrix2F scale(int x, int y);
    IMatrix2F scale(float x, float y);
    IMatrix2F scale(double x, double y);
    IMatrix2F scale(IVec2D vec);
    IMatrix2F scale(IVec2I vec);
    IMatrix2F translate(int x, int y);
    IMatrix2F translate(float x, float y);
    IMatrix2F translate(double x, double y);
    IMatrix2F translate(IVec2D vec);
    IMatrix2F translate(IVec2I vec);
    IMatrix2F rotate(float degrees);
    IMatrix2F rotateAround(int x, int y, float degrees);
    IMatrix2F rotateAround(float x, float y, float degrees);
    IMatrix2F rotateAround(double x, double y, float degrees);
    IMatrix2F rotateAround(IVec2D point, float degrees);
    IMatrix2F rotateAround(IVec2I point, float degrees);
    IVec2I transform(int x, int y);
    IVec2D transform(float x, float y);
    IVec2D transform(double x, double y);
    IVec2I transform(IVec2I vec);
    IVec2IM transform(IVec2IM vec);
    IVec2D transform(IVec2D vec);
    IVec2DM transform(IVec2DM vec);
    IVec2I[] transform(IVec2I... vec);
    IVec2IM[] transform(IVec2IM... vec);
    IVec2D[] transform(IVec2D... vec);
    IVec2DM[] transform(IVec2DM... vec);
    IBox2I transform(IBox2I box);
    IBox2IM transform(IBox2IM box);
    IBox2D transform(IBox2D box);
    IBox2DM transform(IBox2DM box);
    IBox2I[] transform(IBox2I... box);
    IBox2IM[] transform(IBox2IM... box);
    IBox2D[] transform(IBox2D... box);
    IBox2DM[] transform(IBox2DM... box);
    FloatBuffer writeToBuffer(FloatBuffer buf);
    IMatrix2F toImmutable();
    IMatrix2D toDouble();
}
